# Generated by Django 5.0.4 on 2024-05-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"verbose_name": "Счёт", "verbose_name_plural": "Счета"},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Комната", "verbose_name_plural": "Комнаты"},
        ),
        migrations.AddField(
            model_name="room",
            name="description",
            field=models.TextField(default="", verbose_name="Описание номера"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel.reservation",
                verbose_name="Номер брони",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel.room",
                verbose_name="Комната",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="category",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартный номер"),
                    ("superior", "Номер повышенного комфорта"),
                    ("deluxe", "Номер «люкс»"),
                ],
                max_length=50,
                verbose_name="Категория номера",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                choices=[
                    ("single", "Номер с односпальной кроватью"),
                    ("double", "Номер с двуспальной кроватью"),
                    ("twin", "Номер с двумя кроватями"),
                    ("triple", "Номер с тремя кроватями"),
                    ("family", "Семейный номер"),
                ],
                max_length=50,
                verbose_name="Тип номера",
            ),
        ),
    ]
