# Generated by Django 5.0.4 on 2024-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_alter_bill_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(
                default="", max_length=50, verbose_name="Название номера"
            ),
        ),
    ]
